### ISSUE TITLE
PTC Login not working

### ISSUE THREAD

**Issue by Droeftoeter** [Droeftoeter/pokapi#15]
As of 0.57.4, the PTC login doesn't work. Need to resolve this by implementing the new login flow/url.

**Comment by timodejong95** [comment]
Is this related to these errors:

`PHP Fatal error: Uncaught Pokapi\Exception\ThrottledException in vendor/sjaakmoes/pokapi/src/Pokapi/Rpc/Service.php:282
Stack trace:
#0 sjaakmoes/pokapi/src/Pokapi/Rpc/Service.php(285): Pokapi\Rpc\Service->batchExecute(Array, Object(Pokapi\Request\Position), 3)
#1 vendor/sjaakmoes/pokapi/src/Pokapi/Rpc/Service.php(285): Pokapi\Rpc\Service->batchExecute(Array, Object(Pokapi\Request\Position), 2)
#2 vendor/sjaakmoes/pokapi/src/Pokapi/API.php(144): Pokapi\Rpc\Service->batchExecute(Array, Object(Pokapi\Request\Position))
#3 tests/catchable-pokemons.php(21): Pokapi\API->initialize()
#4 {main}
thrown in vendor/sjaakmoes/pokapi/src/Pokapi/Rpc/Service.php on line 282`
